# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    
    main: ./cmd/meeseeks
    binary: meeseeks
    ldflags:
      - "-s -w"
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      # No 32-bit-only targets; windows/arm64 support is niche, skip it.
      - goos: windows
        goarch: arm64

archives:
  - formats:
      - binary
    name_template: "meeseeks_{{ .Tag }}_{{ .Os }}-{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}{{ if eq .Os \"windows\" }}.exe{{ end }}"

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy

homebrew_casks:
  - name: meeseeks
    binaries:
      - meeseeks
    repository:
      owner: GustavoCaso
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/GustavoCaso/meeseeks"
    description: "A simple and lightweight process manager for Go applications and CLI tool that simplify managing background processes"
    hooks:
      post:
        install: |
          if OS.mac?
            binary_name = Hardware::CPU.arm? ? "meeseeks_v#{version}_darwin-arm64" : "meeseeks_v#{version}_darwin-amd64"
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/#{binary_name}"]
          end
